title: Konfy UI
description: A missing suite of Vue components for common tasks.
evergreen: false
markdown:
    toc:
        includeLevel: [1, 2, 3]
themeConfig:
    sidebar:
    - guide
    - vue-button
    - vue-button-alt
    - vue-button-group
    - vue-input
    - vue-input-date
    - vue-select
    - vue-switch
    - vue-file-tray
    - vue-meter
    - vue-google-map
    - vue-google-places
head:
    -
        - script
        - src: https://maps.googleapis.com/maps/api/js?key=AIzaSyBUavk16gEzOiZhnuIdDQCKEgqXpBQb7ks&libraries=places