title: Konfy UI
description: A missing suite of Vue components for common tasks.
evergreen: false
markdown:
    toc:
        includeLevel: [1, 2, 3]
themeConfig:
    nav:
        - text: GitHub
          link: https://github.com/konfyapp/konfy-ui
    sidebar:
        - guide
        - vue-button
        - vue-button-alt
        - vue-button-group
        - vue-input
        - vue-input-date
        - vue-select
        - vue-switch
        - vue-file-tray
        - vue-meter
        - vue-google-map
        - vue-google-places
head:
    -
        - script
        - src: https://maps.googleapis.com/maps/api/js?key=AIzaSyBUavk16gEzOiZhnuIdDQCKEgqXpBQb7ks&libraries=places
    -
        - script
        -
            async: true
            src: https://www.googletagmanager.com/gtag/js?id=UA-129040816-1
    -
        - script
        - src: /js/ga.js
    -
        - meta
        -
            name: google-site-verification
            content: qA72lWZLDHIhlVU6baUVKF3pHUtebckRAJWkWopDvp0
plugins:
    sitemap:
        hostname: https://konfy-ui.netlify.com/
